// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: db.proto

package dbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	RunDate       string                 `protobuf:"bytes,3,opt,name=run_date,json=runDate,proto3" json:"run_date,omitempty"` // YYYY-MM-DD
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`            // BUY | SELL | HOLD
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Summary       string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	FullReport    string                 `protobuf:"bytes,7,opt,name=full_report,json=fullReport,proto3" json:"full_report,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Decision) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

func (x *Decision) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Decision) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Decision) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Decision) GetFullReport() string {
	if x != nil {
		return x.FullReport
	}
	return ""
}

func (x *Decision) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	RunDate       string                 `protobuf:"bytes,2,opt,name=run_date,json=runDate,proto3" json:"run_date,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	FullReport    string                 `protobuf:"bytes,6,opt,name=full_report,json=fullReport,proto3" json:"full_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDecisionRequest) Reset() {
	*x = CreateDecisionRequest{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecisionRequest) ProtoMessage() {}

func (x *CreateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecisionRequest.ProtoReflect.Descriptor instead.
func (*CreateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDecisionRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *CreateDecisionRequest) GetRunDate() string {
	if x != nil {
		return x.RunDate
	}
	return ""
}

func (x *CreateDecisionRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateDecisionRequest) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CreateDecisionRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateDecisionRequest) GetFullReport() string {
	if x != nil {
		return x.FullReport
	}
	return ""
}

type CreateDecisionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDecisionReply) Reset() {
	*x = CreateDecisionReply{}
	mi := &file_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDecisionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecisionReply) ProtoMessage() {}

func (x *CreateDecisionReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecisionReply.ProtoReflect.Descriptor instead.
func (*CreateDecisionReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDecisionReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDecisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{3}
}

func (x *ListDecisionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDecisionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsReply) Reset() {
	*x = ListDecisionsReply{}
	mi := &file_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsReply) ProtoMessage() {}

func (x *ListDecisionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsReply.ProtoReflect.Descriptor instead.
func (*ListDecisionsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{4}
}

func (x *ListDecisionsReply) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type Leg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`   // buy | sell
	Right         string                 `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"` // call | put
	Strike        float64                `protobuf:"fixed64,3,opt,name=strike,proto3" json:"strike,omitempty"`
	Expiry        string                 `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"` // YYYY-MM-DD
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"` // OCC option symbol
	RatioQty      int32                  `protobuf:"varint,6,opt,name=ratio_qty,json=ratioQty,proto3" json:"ratio_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{5}
}

func (x *Leg) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Leg) GetRight() string {
	if x != nil {
		return x.Right
	}
	return ""
}

func (x *Leg) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *Leg) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *Leg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Leg) GetRatioQty() int32 {
	if x != nil {
		return x.RatioQty
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Strategy      string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Legs          []*Leg                 `protobuf:"bytes,5,rep,name=legs,proto3" json:"legs,omitempty"`
	Expiry        string                 `protobuf:"bytes,6,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreditDebit   string                 `protobuf:"bytes,8,opt,name=credit_debit,json=creditDebit,proto3" json:"credit_debit,omitempty"` // credit | debit
	NetPremium    float64                `protobuf:"fixed64,9,opt,name=net_premium,json=netPremium,proto3" json:"net_premium,omitempty"`
	MaxProfit     float64                `protobuf:"fixed64,10,opt,name=max_profit,json=maxProfit,proto3" json:"max_profit,omitempty"`
	MaxLoss       float64                `protobuf:"fixed64,11,opt,name=max_loss,json=maxLoss,proto3" json:"max_loss,omitempty"`
	Status        string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"` // proposed | open | closed | rejected | failed
	AlpacaOrderId string                 `protobuf:"bytes,13,opt,name=alpaca_order_id,json=alpacaOrderId,proto3" json:"alpaca_order_id,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,14,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	Rationale     string                 `protobuf:"bytes,15,opt,name=rationale,proto3" json:"rationale,omitempty"`
	OpenedAt      string                 `protobuf:"bytes,16,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	ClosedAt      string                 `protobuf:"bytes,17,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{6}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *Trade) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Trade) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Trade) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Trade) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *Trade) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetCreditDebit() string {
	if x != nil {
		return x.CreditDebit
	}
	return ""
}

func (x *Trade) GetNetPremium() float64 {
	if x != nil {
		return x.NetPremium
	}
	return 0
}

func (x *Trade) GetMaxProfit() float64 {
	if x != nil {
		return x.MaxProfit
	}
	return 0
}

func (x *Trade) GetMaxLoss() float64 {
	if x != nil {
		return x.MaxLoss
	}
	return 0
}

func (x *Trade) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trade) GetAlpacaOrderId() string {
	if x != nil {
		return x.AlpacaOrderId
	}
	return ""
}

func (x *Trade) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *Trade) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *Trade) GetOpenedAt() string {
	if x != nil {
		return x.OpenedAt
	}
	return ""
}

func (x *Trade) GetClosedAt() string {
	if x != nil {
		return x.ClosedAt
	}
	return ""
}

func (x *Trade) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateTradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Legs          []*Leg                 `protobuf:"bytes,4,rep,name=legs,proto3" json:"legs,omitempty"`
	Expiry        string                 `protobuf:"bytes,5,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreditDebit   string                 `protobuf:"bytes,7,opt,name=credit_debit,json=creditDebit,proto3" json:"credit_debit,omitempty"`
	NetPremium    float64                `protobuf:"fixed64,8,opt,name=net_premium,json=netPremium,proto3" json:"net_premium,omitempty"`
	MaxProfit     float64                `protobuf:"fixed64,9,opt,name=max_profit,json=maxProfit,proto3" json:"max_profit,omitempty"`
	MaxLoss       float64                `protobuf:"fixed64,10,opt,name=max_loss,json=maxLoss,proto3" json:"max_loss,omitempty"`
	Rationale     string                 `protobuf:"bytes,11,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTradeRequest) Reset() {
	*x = CreateTradeRequest{}
	mi := &file_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRequest) ProtoMessage() {}

func (x *CreateTradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRequest.ProtoReflect.Descriptor instead.
func (*CreateTradeRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTradeRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CreateTradeRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *CreateTradeRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *CreateTradeRequest) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *CreateTradeRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CreateTradeRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateTradeRequest) GetCreditDebit() string {
	if x != nil {
		return x.CreditDebit
	}
	return ""
}

func (x *CreateTradeRequest) GetNetPremium() float64 {
	if x != nil {
		return x.NetPremium
	}
	return 0
}

func (x *CreateTradeRequest) GetMaxProfit() float64 {
	if x != nil {
		return x.MaxProfit
	}
	return 0
}

func (x *CreateTradeRequest) GetMaxLoss() float64 {
	if x != nil {
		return x.MaxLoss
	}
	return 0
}

func (x *CreateTradeRequest) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type CreateTradeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTradeReply) Reset() {
	*x = CreateTradeReply{}
	mi := &file_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTradeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReply) ProtoMessage() {}

func (x *CreateTradeReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReply.ProtoReflect.Descriptor instead.
func (*CreateTradeReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTradeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTradeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AlpacaOrderId string                 `protobuf:"bytes,3,opt,name=alpaca_order_id,json=alpacaOrderId,proto3" json:"alpaca_order_id,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,4,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTradeStatusRequest) Reset() {
	*x = UpdateTradeStatusRequest{}
	mi := &file_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeStatusRequest) ProtoMessage() {}

func (x *UpdateTradeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTradeStatusRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTradeStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetAlpacaOrderId() string {
	if x != nil {
		return x.AlpacaOrderId
	}
	return ""
}

func (x *UpdateTradeStatusRequest) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

type UpdateTradeStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTradeStatusReply) Reset() {
	*x = UpdateTradeStatusReply{}
	mi := &file_db_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTradeStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTradeStatusReply) ProtoMessage() {}

func (x *UpdateTradeStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTradeStatusReply.ProtoReflect.Descriptor instead.
func (*UpdateTradeStatusReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTradeStatusReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "" = all
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_db_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{11}
}

func (x *ListTradesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTradesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTradesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesReply) Reset() {
	*x = ListTradesReply{}
	mi := &file_db_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesReply) ProtoMessage() {}

func (x *ListTradesReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesReply.ProtoReflect.Descriptor instead.
func (*ListTradesReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{12}
}

func (x *ListTradesReply) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type RiskGateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TradeId       string                 `protobuf:"bytes,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	GateName      string                 `protobuf:"bytes,3,opt,name=gate_name,json=gateName,proto3" json:"gate_name,omitempty"`
	Passed        bool                   `protobuf:"varint,4,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskGateEvent) Reset() {
	*x = RiskGateEvent{}
	mi := &file_db_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskGateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskGateEvent) ProtoMessage() {}

func (x *RiskGateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskGateEvent.ProtoReflect.Descriptor instead.
func (*RiskGateEvent) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{13}
}

func (x *RiskGateEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RiskGateEvent) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *RiskGateEvent) GetGateName() string {
	if x != nil {
		return x.GateName
	}
	return ""
}

func (x *RiskGateEvent) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RiskGateEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskGateEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LogRiskGateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	GateName      string                 `protobuf:"bytes,2,opt,name=gate_name,json=gateName,proto3" json:"gate_name,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRiskGateEventRequest) Reset() {
	*x = LogRiskGateEventRequest{}
	mi := &file_db_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRiskGateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRiskGateEventRequest) ProtoMessage() {}

func (x *LogRiskGateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRiskGateEventRequest.ProtoReflect.Descriptor instead.
func (*LogRiskGateEventRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{14}
}

func (x *LogRiskGateEventRequest) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *LogRiskGateEventRequest) GetGateName() string {
	if x != nil {
		return x.GateName
	}
	return ""
}

func (x *LogRiskGateEventRequest) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *LogRiskGateEventRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LogRiskGateEventReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRiskGateEventReply) Reset() {
	*x = LogRiskGateEventReply{}
	mi := &file_db_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRiskGateEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRiskGateEventReply) ProtoMessage() {}

func (x *LogRiskGateEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRiskGateEventReply.ProtoReflect.Descriptor instead.
func (*LogRiskGateEventReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{15}
}

func (x *LogRiskGateEventReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRiskGateEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRiskGateEventsRequest) Reset() {
	*x = ListRiskGateEventsRequest{}
	mi := &file_db_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiskGateEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiskGateEventsRequest) ProtoMessage() {}

func (x *ListRiskGateEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiskGateEventsRequest.ProtoReflect.Descriptor instead.
func (*ListRiskGateEventsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{16}
}

func (x *ListRiskGateEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRiskGateEventsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RiskGateEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRiskGateEventsReply) Reset() {
	*x = ListRiskGateEventsReply{}
	mi := &file_db_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiskGateEventsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiskGateEventsReply) ProtoMessage() {}

func (x *ListRiskGateEventsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiskGateEventsReply.ProtoReflect.Descriptor instead.
func (*ListRiskGateEventsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{17}
}

func (x *ListRiskGateEventsReply) GetEvents() []*RiskGateEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type AccountSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Equity             float64                `protobuf:"fixed64,2,opt,name=equity,proto3" json:"equity,omitempty"`
	Cash               float64                `protobuf:"fixed64,3,opt,name=cash,proto3" json:"cash,omitempty"`
	BuyingPower        float64                `protobuf:"fixed64,4,opt,name=buying_power,json=buyingPower,proto3" json:"buying_power,omitempty"`
	OptionsBuyingPower float64                `protobuf:"fixed64,5,opt,name=options_buying_power,json=optionsBuyingPower,proto3" json:"options_buying_power,omitempty"`
	DayPnl             float64                `protobuf:"fixed64,6,opt,name=day_pnl,json=dayPnl,proto3" json:"day_pnl,omitempty"`
	OpenPositionsCount int32                  `protobuf:"varint,7,opt,name=open_positions_count,json=openPositionsCount,proto3" json:"open_positions_count,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccountSnapshot) Reset() {
	*x = AccountSnapshot{}
	mi := &file_db_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSnapshot) ProtoMessage() {}

func (x *AccountSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSnapshot.ProtoReflect.Descriptor instead.
func (*AccountSnapshot) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{18}
}

func (x *AccountSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountSnapshot) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *AccountSnapshot) GetCash() float64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *AccountSnapshot) GetBuyingPower() float64 {
	if x != nil {
		return x.BuyingPower
	}
	return 0
}

func (x *AccountSnapshot) GetOptionsBuyingPower() float64 {
	if x != nil {
		return x.OptionsBuyingPower
	}
	return 0
}

func (x *AccountSnapshot) GetDayPnl() float64 {
	if x != nil {
		return x.DayPnl
	}
	return 0
}

func (x *AccountSnapshot) GetOpenPositionsCount() int32 {
	if x != nil {
		return x.OpenPositionsCount
	}
	return 0
}

func (x *AccountSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RecordAccountSnapshotRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Equity             float64                `protobuf:"fixed64,1,opt,name=equity,proto3" json:"equity,omitempty"`
	Cash               float64                `protobuf:"fixed64,2,opt,name=cash,proto3" json:"cash,omitempty"`
	BuyingPower        float64                `protobuf:"fixed64,3,opt,name=buying_power,json=buyingPower,proto3" json:"buying_power,omitempty"`
	OptionsBuyingPower float64                `protobuf:"fixed64,4,opt,name=options_buying_power,json=optionsBuyingPower,proto3" json:"options_buying_power,omitempty"`
	DayPnl             float64                `protobuf:"fixed64,5,opt,name=day_pnl,json=dayPnl,proto3" json:"day_pnl,omitempty"`
	OpenPositionsCount int32                  `protobuf:"varint,6,opt,name=open_positions_count,json=openPositionsCount,proto3" json:"open_positions_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordAccountSnapshotRequest) Reset() {
	*x = RecordAccountSnapshotRequest{}
	mi := &file_db_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAccountSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAccountSnapshotRequest) ProtoMessage() {}

func (x *RecordAccountSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAccountSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RecordAccountSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{19}
}

func (x *RecordAccountSnapshotRequest) GetEquity() float64 {
	if x != nil {
		return x.Equity
	}
	return 0
}

func (x *RecordAccountSnapshotRequest) GetCash() float64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *RecordAccountSnapshotRequest) GetBuyingPower() float64 {
	if x != nil {
		return x.BuyingPower
	}
	return 0
}

func (x *RecordAccountSnapshotRequest) GetOptionsBuyingPower() float64 {
	if x != nil {
		return x.OptionsBuyingPower
	}
	return 0
}

func (x *RecordAccountSnapshotRequest) GetDayPnl() float64 {
	if x != nil {
		return x.DayPnl
	}
	return 0
}

func (x *RecordAccountSnapshotRequest) GetOpenPositionsCount() int32 {
	if x != nil {
		return x.OpenPositionsCount
	}
	return 0
}

type RecordAccountSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAccountSnapshotReply) Reset() {
	*x = RecordAccountSnapshotReply{}
	mi := &file_db_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAccountSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAccountSnapshotReply) ProtoMessage() {}

func (x *RecordAccountSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAccountSnapshotReply.ProtoReflect.Descriptor instead.
func (*RecordAccountSnapshotReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{20}
}

func (x *RecordAccountSnapshotReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLatestAccountSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestAccountSnapshotRequest) Reset() {
	*x = GetLatestAccountSnapshotRequest{}
	mi := &file_db_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestAccountSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAccountSnapshotRequest) ProtoMessage() {}

func (x *GetLatestAccountSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAccountSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetLatestAccountSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{21}
}

type ListAccountSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountSnapshotsRequest) Reset() {
	*x = ListAccountSnapshotsRequest{}
	mi := &file_db_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountSnapshotsRequest) ProtoMessage() {}

func (x *ListAccountSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{22}
}

func (x *ListAccountSnapshotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAccountSnapshotsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*AccountSnapshot     `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountSnapshotsReply) Reset() {
	*x = ListAccountSnapshotsReply{}
	mi := &file_db_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountSnapshotsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountSnapshotsReply) ProtoMessage() {}

func (x *ListAccountSnapshotsReply) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountSnapshotsReply.ProtoReflect.Descriptor instead.
func (*ListAccountSnapshotsReply) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{23}
}

func (x *ListAccountSnapshotsReply) GetSnapshots() []*AccountSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\x12\x0emeridian.db.v1\"\xe5\x01\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x19\n" +
	"\brun_date\x18\x03 \x01(\tR\arunDate\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1f\n" +
	"\vfull_report\x18\a \x01(\tR\n" +
	"fullReport\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xc3\x01\n" +
	"\x15CreateDecisionRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x19\n" +
	"\brun_date\x18\x02 \x01(\tR\arunDate\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1f\n" +
	"\vfull_report\x18\x06 \x01(\tR\n" +
	"fullReport\"%\n" +
	"\x13CreateDecisionReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x14ListDecisionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"L\n" +
	"\x12ListDecisionsReply\x126\n" +
	"\tdecisions\x18\x01 \x03(\v2\x18.meridian.db.v1.DecisionR\tdecisions\"\x94\x01\n" +
	"\x03Leg\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12\x14\n" +
	"\x05right\x18\x02 \x01(\tR\x05right\x12\x16\n" +
	"\x06strike\x18\x03 \x01(\x01R\x06strike\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tratio_qty\x18\x06 \x01(\x05R\bratioQty\"\xa1\x04\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12'\n" +
	"\x04legs\x18\x05 \x03(\v2\x13.meridian.db.v1.LegR\x04legs\x12\x16\n" +
	"\x06expiry\x18\x06 \x01(\tR\x06expiry\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12!\n" +
	"\fcredit_debit\x18\b \x01(\tR\vcreditDebit\x12\x1f\n" +
	"\vnet_premium\x18\t \x01(\x01R\n" +
	"netPremium\x12\x1d\n" +
	"\n" +
	"max_profit\x18\n" +
	" \x01(\x01R\tmaxProfit\x12\x19\n" +
	"\bmax_loss\x18\v \x01(\x01R\amaxLoss\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12&\n" +
	"\x0falpaca_order_id\x18\r \x01(\tR\ralpacaOrderId\x12!\n" +
	"\frealized_pnl\x18\x0e \x01(\x01R\vrealizedPnl\x12\x1c\n" +
	"\trationale\x18\x0f \x01(\tR\trationale\x12\x1b\n" +
	"\topened_at\x18\x10 \x01(\tR\bopenedAt\x12\x1b\n" +
	"\tclosed_at\x18\x11 \x01(\tR\bclosedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\"\xe2\x02\n" +
	"\x12CreateTradeRequest\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12'\n" +
	"\x04legs\x18\x04 \x03(\v2\x13.meridian.db.v1.LegR\x04legs\x12\x16\n" +
	"\x06expiry\x18\x05 \x01(\tR\x06expiry\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12!\n" +
	"\fcredit_debit\x18\a \x01(\tR\vcreditDebit\x12\x1f\n" +
	"\vnet_premium\x18\b \x01(\x01R\n" +
	"netPremium\x12\x1d\n" +
	"\n" +
	"max_profit\x18\t \x01(\x01R\tmaxProfit\x12\x19\n" +
	"\bmax_loss\x18\n" +
	" \x01(\x01R\amaxLoss\x12\x1c\n" +
	"\trationale\x18\v \x01(\tR\trationale\"\"\n" +
	"\x10CreateTradeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8d\x01\n" +
	"\x18UpdateTradeStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12&\n" +
	"\x0falpaca_order_id\x18\x03 \x01(\tR\ralpacaOrderId\x12!\n" +
	"\frealized_pnl\x18\x04 \x01(\x01R\vrealizedPnl\"(\n" +
	"\x16UpdateTradeStatusReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"A\n" +
	"\x11ListTradesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"@\n" +
	"\x0fListTradesReply\x12-\n" +
	"\x06trades\x18\x01 \x03(\v2\x15.meridian.db.v1.TradeR\x06trades\"\xa6\x01\n" +
	"\rRiskGateEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\tR\atradeId\x12\x1b\n" +
	"\tgate_name\x18\x03 \x01(\tR\bgateName\x12\x16\n" +
	"\x06passed\x18\x04 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x81\x01\n" +
	"\x17LogRiskGateEventRequest\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x1b\n" +
	"\tgate_name\x18\x02 \x01(\tR\bgateName\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"'\n" +
	"\x15LogRiskGateEventReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x19ListRiskGateEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"P\n" +
	"\x17ListRiskGateEventsReply\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.meridian.db.v1.RiskGateEventR\x06events\"\x8c\x02\n" +
	"\x0fAccountSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06equity\x18\x02 \x01(\x01R\x06equity\x12\x12\n" +
	"\x04cash\x18\x03 \x01(\x01R\x04cash\x12!\n" +
	"\fbuying_power\x18\x04 \x01(\x01R\vbuyingPower\x120\n" +
	"\x14options_buying_power\x18\x05 \x01(\x01R\x12optionsBuyingPower\x12\x17\n" +
	"\aday_pnl\x18\x06 \x01(\x01R\x06dayPnl\x120\n" +
	"\x14open_positions_count\x18\a \x01(\x05R\x12openPositionsCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xea\x01\n" +
	"\x1cRecordAccountSnapshotRequest\x12\x16\n" +
	"\x06equity\x18\x01 \x01(\x01R\x06equity\x12\x12\n" +
	"\x04cash\x18\x02 \x01(\x01R\x04cash\x12!\n" +
	"\fbuying_power\x18\x03 \x01(\x01R\vbuyingPower\x120\n" +
	"\x14options_buying_power\x18\x04 \x01(\x01R\x12optionsBuyingPower\x12\x17\n" +
	"\aday_pnl\x18\x05 \x01(\x01R\x06dayPnl\x120\n" +
	"\x14open_positions_count\x18\x06 \x01(\x05R\x12openPositionsCount\",\n" +
	"\x1aRecordAccountSnapshotReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x1fGetLatestAccountSnapshotRequest\"3\n" +
	"\x1bListAccountSnapshotsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"Z\n" +
	"\x19ListAccountSnapshotsReply\x12=\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x1f.meridian.db.v1.AccountSnapshotR\tsnapshots2\xea\a\n" +
	"\x02Db\x12\\\n" +
	"\x0eCreateDecision\x12%.meridian.db.v1.CreateDecisionRequest\x1a#.meridian.db.v1.CreateDecisionReply\x12Y\n" +
	"\rListDecisions\x12$.meridian.db.v1.ListDecisionsRequest\x1a\".meridian.db.v1.ListDecisionsReply\x12S\n" +
	"\vCreateTrade\x12\".meridian.db.v1.CreateTradeRequest\x1a .meridian.db.v1.CreateTradeReply\x12e\n" +
	"\x11UpdateTradeStatus\x12(.meridian.db.v1.UpdateTradeStatusRequest\x1a&.meridian.db.v1.UpdateTradeStatusReply\x12P\n" +
	"\n" +
	"ListTrades\x12!.meridian.db.v1.ListTradesRequest\x1a\x1f.meridian.db.v1.ListTradesReply\x12b\n" +
	"\x10LogRiskGateEvent\x12'.meridian.db.v1.LogRiskGateEventRequest\x1a%.meridian.db.v1.LogRiskGateEventReply\x12h\n" +
	"\x12ListRiskGateEvents\x12).meridian.db.v1.ListRiskGateEventsRequest\x1a'.meridian.db.v1.ListRiskGateEventsReply\x12q\n" +
	"\x15RecordAccountSnapshot\x12,.meridian.db.v1.RecordAccountSnapshotRequest\x1a*.meridian.db.v1.RecordAccountSnapshotReply\x12l\n" +
	"\x18GetLatestAccountSnapshot\x12/.meridian.db.v1.GetLatestAccountSnapshotRequest\x1a\x1f.meridian.db.v1.AccountSnapshot\x12n\n" +
	"\x14ListAccountSnapshots\x12+.meridian.db.v1.ListAccountSnapshotsRequest\x1a).meridian.db.v1.ListAccountSnapshotsReplyB8Z6github.com/idk4whatamiusing/meridian_stack/api/pb/dbpbb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_db_proto_goTypes = []any{
	(*Decision)(nil),                        // 0: meridian.db.v1.Decision
	(*CreateDecisionRequest)(nil),           // 1: meridian.db.v1.CreateDecisionRequest
	(*CreateDecisionReply)(nil),             // 2: meridian.db.v1.CreateDecisionReply
	(*ListDecisionsRequest)(nil),            // 3: meridian.db.v1.ListDecisionsRequest
	(*ListDecisionsReply)(nil),              // 4: meridian.db.v1.ListDecisionsReply
	(*Leg)(nil),                             // 5: meridian.db.v1.Leg
	(*Trade)(nil),                           // 6: meridian.db.v1.Trade
	(*CreateTradeRequest)(nil),              // 7: meridian.db.v1.CreateTradeRequest
	(*CreateTradeReply)(nil),                // 8: meridian.db.v1.CreateTradeReply
	(*UpdateTradeStatusRequest)(nil),        // 9: meridian.db.v1.UpdateTradeStatusRequest
	(*UpdateTradeStatusReply)(nil),          // 10: meridian.db.v1.UpdateTradeStatusReply
	(*ListTradesRequest)(nil),               // 11: meridian.db.v1.ListTradesRequest
	(*ListTradesReply)(nil),                 // 12: meridian.db.v1.ListTradesReply
	(*RiskGateEvent)(nil),                   // 13: meridian.db.v1.RiskGateEvent
	(*LogRiskGateEventRequest)(nil),         // 14: meridian.db.v1.LogRiskGateEventRequest
	(*LogRiskGateEventReply)(nil),           // 15: meridian.db.v1.LogRiskGateEventReply
	(*ListRiskGateEventsRequest)(nil),       // 16: meridian.db.v1.ListRiskGateEventsRequest
	(*ListRiskGateEventsReply)(nil),         // 17: meridian.db.v1.ListRiskGateEventsReply
	(*AccountSnapshot)(nil),                 // 18: meridian.db.v1.AccountSnapshot
	(*RecordAccountSnapshotRequest)(nil),    // 19: meridian.db.v1.RecordAccountSnapshotRequest
	(*RecordAccountSnapshotReply)(nil),      // 20: meridian.db.v1.RecordAccountSnapshotReply
	(*GetLatestAccountSnapshotRequest)(nil), // 21: meridian.db.v1.GetLatestAccountSnapshotRequest
	(*ListAccountSnapshotsRequest)(nil),     // 22: meridian.db.v1.ListAccountSnapshotsRequest
	(*ListAccountSnapshotsReply)(nil),       // 23: meridian.db.v1.ListAccountSnapshotsReply
}
var file_db_proto_depIdxs = []int32{
	0,  // 0: meridian.db.v1.ListDecisionsReply.decisions:type_name -> meridian.db.v1.Decision
	5,  // 1: meridian.db.v1.Trade.legs:type_name -> meridian.db.v1.Leg
	5,  // 2: meridian.db.v1.CreateTradeRequest.legs:type_name -> meridian.db.v1.Leg
	6,  // 3: meridian.db.v1.ListTradesReply.trades:type_name -> meridian.db.v1.Trade
	13, // 4: meridian.db.v1.ListRiskGateEventsReply.events:type_name -> meridian.db.v1.RiskGateEvent
	18, // 5: meridian.db.v1.ListAccountSnapshotsReply.snapshots:type_name -> meridian.db.v1.AccountSnapshot
	1,  // 6: meridian.db.v1.Db.CreateDecision:input_type -> meridian.db.v1.CreateDecisionRequest
	3,  // 7: meridian.db.v1.Db.ListDecisions:input_type -> meridian.db.v1.ListDecisionsRequest
	7,  // 8: meridian.db.v1.Db.CreateTrade:input_type -> meridian.db.v1.CreateTradeRequest
	9,  // 9: meridian.db.v1.Db.UpdateTradeStatus:input_type -> meridian.db.v1.UpdateTradeStatusRequest
	11, // 10: meridian.db.v1.Db.ListTrades:input_type -> meridian.db.v1.ListTradesRequest
	14, // 11: meridian.db.v1.Db.LogRiskGateEvent:input_type -> meridian.db.v1.LogRiskGateEventRequest
	16, // 12: meridian.db.v1.Db.ListRiskGateEvents:input_type -> meridian.db.v1.ListRiskGateEventsRequest
	19, // 13: meridian.db.v1.Db.RecordAccountSnapshot:input_type -> meridian.db.v1.RecordAccountSnapshotRequest
	21, // 14: meridian.db.v1.Db.GetLatestAccountSnapshot:input_type -> meridian.db.v1.GetLatestAccountSnapshotRequest
	22, // 15: meridian.db.v1.Db.ListAccountSnapshots:input_type -> meridian.db.v1.ListAccountSnapshotsRequest
	2,  // 16: meridian.db.v1.Db.CreateDecision:output_type -> meridian.db.v1.CreateDecisionReply
	4,  // 17: meridian.db.v1.Db.ListDecisions:output_type -> meridian.db.v1.ListDecisionsReply
	8,  // 18: meridian.db.v1.Db.CreateTrade:output_type -> meridian.db.v1.CreateTradeReply
	10, // 19: meridian.db.v1.Db.UpdateTradeStatus:output_type -> meridian.db.v1.UpdateTradeStatusReply
	12, // 20: meridian.db.v1.Db.ListTrades:output_type -> meridian.db.v1.ListTradesReply
	15, // 21: meridian.db.v1.Db.LogRiskGateEvent:output_type -> meridian.db.v1.LogRiskGateEventReply
	17, // 22: meridian.db.v1.Db.ListRiskGateEvents:output_type -> meridian.db.v1.ListRiskGateEventsReply
	20, // 23: meridian.db.v1.Db.RecordAccountSnapshot:output_type -> meridian.db.v1.RecordAccountSnapshotReply
	18, // 24: meridian.db.v1.Db.GetLatestAccountSnapshot:output_type -> meridian.db.v1.AccountSnapshot
	23, // 25: meridian.db.v1.Db.ListAccountSnapshots:output_type -> meridian.db.v1.ListAccountSnapshotsReply
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
