// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: db.proto

package dbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Db_CreateDecision_FullMethodName           = "/meridian.db.v1.Db/CreateDecision"
	Db_ListDecisions_FullMethodName            = "/meridian.db.v1.Db/ListDecisions"
	Db_CreateTrade_FullMethodName              = "/meridian.db.v1.Db/CreateTrade"
	Db_UpdateTradeStatus_FullMethodName        = "/meridian.db.v1.Db/UpdateTradeStatus"
	Db_ListTrades_FullMethodName               = "/meridian.db.v1.Db/ListTrades"
	Db_LogRiskGateEvent_FullMethodName         = "/meridian.db.v1.Db/LogRiskGateEvent"
	Db_ListRiskGateEvents_FullMethodName       = "/meridian.db.v1.Db/ListRiskGateEvents"
	Db_RecordAccountSnapshot_FullMethodName    = "/meridian.db.v1.Db/RecordAccountSnapshot"
	Db_GetLatestAccountSnapshot_FullMethodName = "/meridian.db.v1.Db/GetLatestAccountSnapshot"
	Db_ListAccountSnapshots_FullMethodName     = "/meridian.db.v1.Db/ListAccountSnapshots"
)

// DbClient is the client API for Db service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Db is the private Postgres gatekeeper. Callers (Go api, Python ai) must
// carry x-backend-secret.
type DbClient interface {
	CreateDecision(ctx context.Context, in *CreateDecisionRequest, opts ...grpc.CallOption) (*CreateDecisionReply, error)
	ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsReply, error)
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeReply, error)
	UpdateTradeStatus(ctx context.Context, in *UpdateTradeStatusRequest, opts ...grpc.CallOption) (*UpdateTradeStatusReply, error)
	ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesReply, error)
	LogRiskGateEvent(ctx context.Context, in *LogRiskGateEventRequest, opts ...grpc.CallOption) (*LogRiskGateEventReply, error)
	ListRiskGateEvents(ctx context.Context, in *ListRiskGateEventsRequest, opts ...grpc.CallOption) (*ListRiskGateEventsReply, error)
	RecordAccountSnapshot(ctx context.Context, in *RecordAccountSnapshotRequest, opts ...grpc.CallOption) (*RecordAccountSnapshotReply, error)
	GetLatestAccountSnapshot(ctx context.Context, in *GetLatestAccountSnapshotRequest, opts ...grpc.CallOption) (*AccountSnapshot, error)
	ListAccountSnapshots(ctx context.Context, in *ListAccountSnapshotsRequest, opts ...grpc.CallOption) (*ListAccountSnapshotsReply, error)
}

type dbClient struct {
	cc grpc.ClientConnInterface
}

func NewDbClient(cc grpc.ClientConnInterface) DbClient {
	return &dbClient{cc}
}

func (c *dbClient) CreateDecision(ctx context.Context, in *CreateDecisionRequest, opts ...grpc.CallOption) (*CreateDecisionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDecisionReply)
	err := c.cc.Invoke(ctx, Db_CreateDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDecisionsReply)
	err := c.cc.Invoke(ctx, Db_ListDecisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*CreateTradeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTradeReply)
	err := c.cc.Invoke(ctx, Db_CreateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) UpdateTradeStatus(ctx context.Context, in *UpdateTradeStatusRequest, opts ...grpc.CallOption) (*UpdateTradeStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTradeStatusReply)
	err := c.cc.Invoke(ctx, Db_UpdateTradeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesReply)
	err := c.cc.Invoke(ctx, Db_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) LogRiskGateEvent(ctx context.Context, in *LogRiskGateEventRequest, opts ...grpc.CallOption) (*LogRiskGateEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogRiskGateEventReply)
	err := c.cc.Invoke(ctx, Db_LogRiskGateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListRiskGateEvents(ctx context.Context, in *ListRiskGateEventsRequest, opts ...grpc.CallOption) (*ListRiskGateEventsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRiskGateEventsReply)
	err := c.cc.Invoke(ctx, Db_ListRiskGateEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) RecordAccountSnapshot(ctx context.Context, in *RecordAccountSnapshotRequest, opts ...grpc.CallOption) (*RecordAccountSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAccountSnapshotReply)
	err := c.cc.Invoke(ctx, Db_RecordAccountSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) GetLatestAccountSnapshot(ctx context.Context, in *GetLatestAccountSnapshotRequest, opts ...grpc.CallOption) (*AccountSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountSnapshot)
	err := c.cc.Invoke(ctx, Db_GetLatestAccountSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListAccountSnapshots(ctx context.Context, in *ListAccountSnapshotsRequest, opts ...grpc.CallOption) (*ListAccountSnapshotsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountSnapshotsReply)
	err := c.cc.Invoke(ctx, Db_ListAccountSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServer is the server API for Db service.
// All implementations must embed UnimplementedDbServer
// for forward compatibility.
//
// Db is the private Postgres gatekeeper. Callers (Go api, Python ai) must
// carry x-backend-secret.
type DbServer interface {
	CreateDecision(context.Context, *CreateDecisionRequest) (*CreateDecisionReply, error)
	ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsReply, error)
	CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeReply, error)
	UpdateTradeStatus(context.Context, *UpdateTradeStatusRequest) (*UpdateTradeStatusReply, error)
	ListTrades(context.Context, *ListTradesRequest) (*ListTradesReply, error)
	LogRiskGateEvent(context.Context, *LogRiskGateEventRequest) (*LogRiskGateEventReply, error)
	ListRiskGateEvents(context.Context, *ListRiskGateEventsRequest) (*ListRiskGateEventsReply, error)
	RecordAccountSnapshot(context.Context, *RecordAccountSnapshotRequest) (*RecordAccountSnapshotReply, error)
	GetLatestAccountSnapshot(context.Context, *GetLatestAccountSnapshotRequest) (*AccountSnapshot, error)
	ListAccountSnapshots(context.Context, *ListAccountSnapshotsRequest) (*ListAccountSnapshotsReply, error)
	mustEmbedUnimplementedDbServer()
}

// UnimplementedDbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbServer struct{}

func (UnimplementedDbServer) CreateDecision(context.Context, *CreateDecisionRequest) (*CreateDecisionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDecision not implemented")
}
func (UnimplementedDbServer) ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDecisions not implemented")
}
func (UnimplementedDbServer) CreateTrade(context.Context, *CreateTradeRequest) (*CreateTradeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedDbServer) UpdateTradeStatus(context.Context, *UpdateTradeStatusRequest) (*UpdateTradeStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTradeStatus not implemented")
}
func (UnimplementedDbServer) ListTrades(context.Context, *ListTradesRequest) (*ListTradesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedDbServer) LogRiskGateEvent(context.Context, *LogRiskGateEventRequest) (*LogRiskGateEventReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LogRiskGateEvent not implemented")
}
func (UnimplementedDbServer) ListRiskGateEvents(context.Context, *ListRiskGateEventsRequest) (*ListRiskGateEventsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRiskGateEvents not implemented")
}
func (UnimplementedDbServer) RecordAccountSnapshot(context.Context, *RecordAccountSnapshotRequest) (*RecordAccountSnapshotReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAccountSnapshot not implemented")
}
func (UnimplementedDbServer) GetLatestAccountSnapshot(context.Context, *GetLatestAccountSnapshotRequest) (*AccountSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestAccountSnapshot not implemented")
}
func (UnimplementedDbServer) ListAccountSnapshots(context.Context, *ListAccountSnapshotsRequest) (*ListAccountSnapshotsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccountSnapshots not implemented")
}
func (UnimplementedDbServer) mustEmbedUnimplementedDbServer() {}
func (UnimplementedDbServer) testEmbeddedByValue()            {}

// UnsafeDbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServer will
// result in compilation errors.
type UnsafeDbServer interface {
	mustEmbedUnimplementedDbServer()
}

func RegisterDbServer(s grpc.ServiceRegistrar, srv DbServer) {
	// If the following call panics, it indicates UnimplementedDbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Db_ServiceDesc, srv)
}

func _Db_CreateDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).CreateDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_CreateDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).CreateDecision(ctx, req.(*CreateDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListDecisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDecisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListDecisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListDecisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListDecisions(ctx, req.(*ListDecisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_CreateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_UpdateTradeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTradeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).UpdateTradeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_UpdateTradeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).UpdateTradeStatus(ctx, req.(*UpdateTradeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListTrades(ctx, req.(*ListTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_LogRiskGateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRiskGateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).LogRiskGateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_LogRiskGateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).LogRiskGateEvent(ctx, req.(*LogRiskGateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListRiskGateEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRiskGateEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListRiskGateEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListRiskGateEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListRiskGateEvents(ctx, req.(*ListRiskGateEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_RecordAccountSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAccountSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).RecordAccountSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_RecordAccountSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).RecordAccountSnapshot(ctx, req.(*RecordAccountSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_GetLatestAccountSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestAccountSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).GetLatestAccountSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_GetLatestAccountSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).GetLatestAccountSnapshot(ctx, req.(*GetLatestAccountSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListAccountSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListAccountSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListAccountSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListAccountSnapshots(ctx, req.(*ListAccountSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Db_ServiceDesc is the grpc.ServiceDesc for Db service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Db_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.db.v1.Db",
	HandlerType: (*DbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDecision",
			Handler:    _Db_CreateDecision_Handler,
		},
		{
			MethodName: "ListDecisions",
			Handler:    _Db_ListDecisions_Handler,
		},
		{
			MethodName: "CreateTrade",
			Handler:    _Db_CreateTrade_Handler,
		},
		{
			MethodName: "UpdateTradeStatus",
			Handler:    _Db_UpdateTradeStatus_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _Db_ListTrades_Handler,
		},
		{
			MethodName: "LogRiskGateEvent",
			Handler:    _Db_LogRiskGateEvent_Handler,
		},
		{
			MethodName: "ListRiskGateEvents",
			Handler:    _Db_ListRiskGateEvents_Handler,
		},
		{
			MethodName: "RecordAccountSnapshot",
			Handler:    _Db_RecordAccountSnapshot_Handler,
		},
		{
			MethodName: "GetLatestAccountSnapshot",
			Handler:    _Db_GetLatestAccountSnapshot_Handler,
		},
		{
			MethodName: "ListAccountSnapshots",
			Handler:    _Db_ListAccountSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
