// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: db.proto

package dbpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Db_UpsertUser_FullMethodName        = "/meridian.db.v1.Db/UpsertUser"
	Db_ListUsers_FullMethodName         = "/meridian.db.v1.Db/ListUsers"
	Db_CreateChatSession_FullMethodName = "/meridian.db.v1.Db/CreateChatSession"
	Db_ListChatSessions_FullMethodName  = "/meridian.db.v1.Db/ListChatSessions"
	Db_RenameChatSession_FullMethodName = "/meridian.db.v1.Db/RenameChatSession"
	Db_DeleteChatSession_FullMethodName = "/meridian.db.v1.Db/DeleteChatSession"
	Db_AppendChatMessage_FullMethodName = "/meridian.db.v1.Db/AppendChatMessage"
	Db_ListChatMessages_FullMethodName  = "/meridian.db.v1.Db/ListChatMessages"
)

// DbClient is the client API for Db service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Db is the private Postgres gatekeeper. Only the Go api talks to it.
type DbClient interface {
	UpsertUser(ctx context.Context, in *UpsertUserRequest, opts ...grpc.CallOption) (*UpsertUserReply, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error)
	// chat sessions + history (Postgres is primary; Redis in api is the 7d cache)
	CreateChatSession(ctx context.Context, in *CreateChatSessionRequest, opts ...grpc.CallOption) (*CreateChatSessionReply, error)
	ListChatSessions(ctx context.Context, in *ListChatSessionsRequest, opts ...grpc.CallOption) (*ListChatSessionsReply, error)
	RenameChatSession(ctx context.Context, in *RenameChatSessionRequest, opts ...grpc.CallOption) (*RenameChatSessionReply, error)
	DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*DeleteChatSessionReply, error)
	AppendChatMessage(ctx context.Context, in *AppendChatMessageRequest, opts ...grpc.CallOption) (*AppendChatMessageReply, error)
	ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesReply, error)
}

type dbClient struct {
	cc grpc.ClientConnInterface
}

func NewDbClient(cc grpc.ClientConnInterface) DbClient {
	return &dbClient{cc}
}

func (c *dbClient) UpsertUser(ctx context.Context, in *UpsertUserRequest, opts ...grpc.CallOption) (*UpsertUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertUserReply)
	err := c.cc.Invoke(ctx, Db_UpsertUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersReply)
	err := c.cc.Invoke(ctx, Db_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) CreateChatSession(ctx context.Context, in *CreateChatSessionRequest, opts ...grpc.CallOption) (*CreateChatSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatSessionReply)
	err := c.cc.Invoke(ctx, Db_CreateChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListChatSessions(ctx context.Context, in *ListChatSessionsRequest, opts ...grpc.CallOption) (*ListChatSessionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatSessionsReply)
	err := c.cc.Invoke(ctx, Db_ListChatSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) RenameChatSession(ctx context.Context, in *RenameChatSessionRequest, opts ...grpc.CallOption) (*RenameChatSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameChatSessionReply)
	err := c.cc.Invoke(ctx, Db_RenameChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) DeleteChatSession(ctx context.Context, in *DeleteChatSessionRequest, opts ...grpc.CallOption) (*DeleteChatSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatSessionReply)
	err := c.cc.Invoke(ctx, Db_DeleteChatSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) AppendChatMessage(ctx context.Context, in *AppendChatMessageRequest, opts ...grpc.CallOption) (*AppendChatMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendChatMessageReply)
	err := c.cc.Invoke(ctx, Db_AppendChatMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChatMessagesReply)
	err := c.cc.Invoke(ctx, Db_ListChatMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServer is the server API for Db service.
// All implementations must embed UnimplementedDbServer
// for forward compatibility.
//
// Db is the private Postgres gatekeeper. Only the Go api talks to it.
type DbServer interface {
	UpsertUser(context.Context, *UpsertUserRequest) (*UpsertUserReply, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersReply, error)
	// chat sessions + history (Postgres is primary; Redis in api is the 7d cache)
	CreateChatSession(context.Context, *CreateChatSessionRequest) (*CreateChatSessionReply, error)
	ListChatSessions(context.Context, *ListChatSessionsRequest) (*ListChatSessionsReply, error)
	RenameChatSession(context.Context, *RenameChatSessionRequest) (*RenameChatSessionReply, error)
	DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*DeleteChatSessionReply, error)
	AppendChatMessage(context.Context, *AppendChatMessageRequest) (*AppendChatMessageReply, error)
	ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesReply, error)
	mustEmbedUnimplementedDbServer()
}

// UnimplementedDbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDbServer struct{}

func (UnimplementedDbServer) UpsertUser(context.Context, *UpsertUserRequest) (*UpsertUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUser not implemented")
}
func (UnimplementedDbServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedDbServer) CreateChatSession(context.Context, *CreateChatSessionRequest) (*CreateChatSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatSession not implemented")
}
func (UnimplementedDbServer) ListChatSessions(context.Context, *ListChatSessionsRequest) (*ListChatSessionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatSessions not implemented")
}
func (UnimplementedDbServer) RenameChatSession(context.Context, *RenameChatSessionRequest) (*RenameChatSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameChatSession not implemented")
}
func (UnimplementedDbServer) DeleteChatSession(context.Context, *DeleteChatSessionRequest) (*DeleteChatSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChatSession not implemented")
}
func (UnimplementedDbServer) AppendChatMessage(context.Context, *AppendChatMessageRequest) (*AppendChatMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendChatMessage not implemented")
}
func (UnimplementedDbServer) ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatMessages not implemented")
}
func (UnimplementedDbServer) mustEmbedUnimplementedDbServer() {}
func (UnimplementedDbServer) testEmbeddedByValue()            {}

// UnsafeDbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DbServer will
// result in compilation errors.
type UnsafeDbServer interface {
	mustEmbedUnimplementedDbServer()
}

func RegisterDbServer(s grpc.ServiceRegistrar, srv DbServer) {
	// If the following call pancis, it indicates UnimplementedDbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Db_ServiceDesc, srv)
}

func _Db_UpsertUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).UpsertUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_UpsertUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).UpsertUser(ctx, req.(*UpsertUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_CreateChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).CreateChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_CreateChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).CreateChatSession(ctx, req.(*CreateChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListChatSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListChatSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListChatSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListChatSessions(ctx, req.(*ListChatSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_RenameChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).RenameChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_RenameChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).RenameChatSession(ctx, req.(*RenameChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_DeleteChatSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).DeleteChatSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_DeleteChatSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).DeleteChatSession(ctx, req.(*DeleteChatSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_AppendChatMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendChatMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).AppendChatMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_AppendChatMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).AppendChatMessage(ctx, req.(*AppendChatMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ListChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ListChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Db_ListChatMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ListChatMessages(ctx, req.(*ListChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Db_ServiceDesc is the grpc.ServiceDesc for Db service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Db_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.db.v1.Db",
	HandlerType: (*DbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertUser",
			Handler:    _Db_UpsertUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Db_ListUsers_Handler,
		},
		{
			MethodName: "CreateChatSession",
			Handler:    _Db_CreateChatSession_Handler,
		},
		{
			MethodName: "ListChatSessions",
			Handler:    _Db_ListChatSessions_Handler,
		},
		{
			MethodName: "RenameChatSession",
			Handler:    _Db_RenameChatSession_Handler,
		},
		{
			MethodName: "DeleteChatSession",
			Handler:    _Db_DeleteChatSession_Handler,
		},
		{
			MethodName: "AppendChatMessage",
			Handler:    _Db_AppendChatMessage_Handler,
		},
		{
			MethodName: "ListChatMessages",
			Handler:    _Db_ListChatMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
