package graph

import (
	"github.com/idk4whatamiusing/meridian_stack/api/internal/clients"
	"github.com/idk4whatamiusing/meridian_stack/api/internal/hub"
)

// This file will not be regenerated by gqlgen.
type Resolver struct {
	Clients *clients.Clients
	Hub     *hub.Hub
}
