// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []string               `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"` // empty = configured watchlist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCycleRequest) Reset() {
	*x = RunCycleRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCycleRequest) ProtoMessage() {}

func (x *RunCycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCycleRequest.ProtoReflect.Descriptor instead.
func (*RunCycleRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *RunCycleRequest) GetTickers() []string {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type RunCycleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CycleId       string                 `protobuf:"bytes,1,opt,name=cycle_id,json=cycleId,proto3" json:"cycle_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCycleReply) Reset() {
	*x = RunCycleReply{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCycleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCycleReply) ProtoMessage() {}

func (x *RunCycleReply) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCycleReply.ProtoReflect.Descriptor instead.
func (*RunCycleReply) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *RunCycleReply) GetCycleId() string {
	if x != nil {
		return x.CycleId
	}
	return ""
}

func (x *RunCycleReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetLastCycleResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastCycleResultRequest) Reset() {
	*x = GetLastCycleResultRequest{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastCycleResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastCycleResultRequest) ProtoMessage() {}

func (x *GetLastCycleResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastCycleResultRequest.ProtoReflect.Descriptor instead.
func (*GetLastCycleResultRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

type CycleResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CycleId          string                 `protobuf:"bytes,1,opt,name=cycle_id,json=cycleId,proto3" json:"cycle_id,omitempty"`
	StartedAt        string                 `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       string                 `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	TickersEvaluated int32                  `protobuf:"varint,4,opt,name=tickers_evaluated,json=tickersEvaluated,proto3" json:"tickers_evaluated,omitempty"`
	TradesProposed   int32                  `protobuf:"varint,5,opt,name=trades_proposed,json=tradesProposed,proto3" json:"trades_proposed,omitempty"`
	TradesPlaced     int32                  `protobuf:"varint,6,opt,name=trades_placed,json=tradesPlaced,proto3" json:"trades_placed,omitempty"`
	TradesBlocked    int32                  `protobuf:"varint,7,opt,name=trades_blocked,json=tradesBlocked,proto3" json:"trades_blocked,omitempty"`
	Errors           []string               `protobuf:"bytes,8,rep,name=errors,proto3" json:"errors,omitempty"`
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"` // running | ok | error | idle
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CycleResult) Reset() {
	*x = CycleResult{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CycleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleResult) ProtoMessage() {}

func (x *CycleResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleResult.ProtoReflect.Descriptor instead.
func (*CycleResult) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *CycleResult) GetCycleId() string {
	if x != nil {
		return x.CycleId
	}
	return ""
}

func (x *CycleResult) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *CycleResult) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *CycleResult) GetTickersEvaluated() int32 {
	if x != nil {
		return x.TickersEvaluated
	}
	return 0
}

func (x *CycleResult) GetTradesProposed() int32 {
	if x != nil {
		return x.TradesProposed
	}
	return 0
}

func (x *CycleResult) GetTradesPlaced() int32 {
	if x != nil {
		return x.TradesPlaced
	}
	return 0
}

func (x *CycleResult) GetTradesBlocked() int32 {
	if x != nil {
		return x.TradesBlocked
	}
	return 0
}

func (x *CycleResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CycleResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x0emeridian.ai.v1\"+\n" +
	"\x0fRunCycleRequest\x12\x18\n" +
	"\atickers\x18\x01 \x03(\tR\atickers\"B\n" +
	"\rRunCycleReply\x12\x19\n" +
	"\bcycle_id\x18\x01 \x01(\tR\acycleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1b\n" +
	"\x19GetLastCycleResultRequest\"\xba\x02\n" +
	"\vCycleResult\x12\x19\n" +
	"\bcycle_id\x18\x01 \x01(\tR\acycleId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x02 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x03 \x01(\tR\n" +
	"finishedAt\x12+\n" +
	"\x11tickers_evaluated\x18\x04 \x01(\x05R\x10tickersEvaluated\x12'\n" +
	"\x0ftrades_proposed\x18\x05 \x01(\x05R\x0etradesProposed\x12#\n" +
	"\rtrades_placed\x18\x06 \x01(\x05R\ftradesPlaced\x12%\n" +
	"\x0etrades_blocked\x18\a \x01(\x05R\rtradesBlocked\x12\x16\n" +
	"\x06errors\x18\b \x03(\tR\x06errors\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status2\xae\x01\n" +
	"\x02Ai\x12J\n" +
	"\bRunCycle\x12\x1f.meridian.ai.v1.RunCycleRequest\x1a\x1d.meridian.ai.v1.RunCycleReply\x12\\\n" +
	"\x12GetLastCycleResult\x12).meridian.ai.v1.GetLastCycleResultRequest\x1a\x1b.meridian.ai.v1.CycleResultB8Z6github.com/idk4whatamiusing/meridian_stack/api/pb/aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_proto_goTypes = []any{
	(*RunCycleRequest)(nil),           // 0: meridian.ai.v1.RunCycleRequest
	(*RunCycleReply)(nil),             // 1: meridian.ai.v1.RunCycleReply
	(*GetLastCycleResultRequest)(nil), // 2: meridian.ai.v1.GetLastCycleResultRequest
	(*CycleResult)(nil),               // 3: meridian.ai.v1.CycleResult
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: meridian.ai.v1.Ai.RunCycle:input_type -> meridian.ai.v1.RunCycleRequest
	2, // 1: meridian.ai.v1.Ai.GetLastCycleResult:input_type -> meridian.ai.v1.GetLastCycleResultRequest
	1, // 2: meridian.ai.v1.Ai.RunCycle:output_type -> meridian.ai.v1.RunCycleReply
	3, // 3: meridian.ai.v1.Ai.GetLastCycleResult:output_type -> meridian.ai.v1.CycleResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
