// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ai.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ai_Chat_FullMethodName         = "/meridian.ai.v1.Ai/Chat"
	Ai_ChatStream_FullMethodName   = "/meridian.ai.v1.Ai/ChatStream"
	Ai_SupportQuery_FullMethodName = "/meridian.ai.v1.Ai/SupportQuery"
	Ai_Ingest_FullMethodName       = "/meridian.ai.v1.Ai/Ingest"
	Ai_Predict_FullMethodName      = "/meridian.ai.v1.Ai/Predict"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ai owns ALL AI work: RAG (Python), LLM providers - Cloudflare Workers AI /
// Bedrock (Go), and the local knowledge-base-only support LLM.
type AiClient interface {
	// general chat: provider-aware, RAG-augmented
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatReply, error)
	ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
	// support: knowledge-base-only, local TinyLlama Q4 via llama.cpp
	SupportQuery(ctx context.Context, in *SupportQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SupportChunk], error)
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestReply, error)
	// baseline classifier (kept from the original template)
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatReply)
	err := c.cc.Invoke(ctx, Ai_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) ChatStream(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ai_ServiceDesc.Streams[0], Ai_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_ChatStreamClient = grpc.ServerStreamingClient[ChatChunk]

func (c *aiClient) SupportQuery(ctx context.Context, in *SupportQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SupportChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Ai_ServiceDesc.Streams[1], Ai_SupportQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SupportQueryRequest, SupportChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_SupportQueryClient = grpc.ServerStreamingClient[SupportChunk]

func (c *aiClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestReply)
	err := c.cc.Invoke(ctx, Ai_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictReply)
	err := c.cc.Invoke(ctx, Ai_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility.
//
// Ai owns ALL AI work: RAG (Python), LLM providers - Cloudflare Workers AI /
// Bedrock (Go), and the local knowledge-base-only support LLM.
type AiServer interface {
	// general chat: provider-aware, RAG-augmented
	Chat(context.Context, *ChatRequest) (*ChatReply, error)
	ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
	// support: knowledge-base-only, local TinyLlama Q4 via llama.cpp
	SupportQuery(*SupportQueryRequest, grpc.ServerStreamingServer[SupportChunk]) error
	Ingest(context.Context, *IngestRequest) (*IngestReply, error)
	// baseline classifier (kept from the original template)
	Predict(context.Context, *PredictRequest) (*PredictReply, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServer struct{}

func (UnimplementedAiServer) Chat(context.Context, *ChatRequest) (*ChatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAiServer) ChatStream(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedAiServer) SupportQuery(*SupportQueryRequest, grpc.ServerStreamingServer[SupportChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SupportQuery not implemented")
}
func (UnimplementedAiServer) Ingest(context.Context, *IngestRequest) (*IngestReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedAiServer) Predict(context.Context, *PredictRequest) (*PredictReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}
func (UnimplementedAiServer) testEmbeddedByValue()            {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	// If the following call pancis, it indicates UnimplementedAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiServer).ChatStream(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_ChatStreamServer = grpc.ServerStreamingServer[ChatChunk]

func _Ai_SupportQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SupportQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiServer).SupportQuery(m, &grpc.GenericServerStream[SupportQueryRequest, SupportChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Ai_SupportQueryServer = grpc.ServerStreamingServer[SupportChunk]

func _Ai_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meridian.ai.v1.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _Ai_Chat_Handler,
		},
		{
			MethodName: "Ingest",
			Handler:    _Ai_Ingest_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _Ai_Predict_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _Ai_ChatStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SupportQuery",
			Handler:       _Ai_SupportQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
