// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package app

type ChatChunk struct {
	Delta   string    `json:"delta"`
	Done    bool      `json:"done"`
	Sources []*Source `json:"sources"`
	Cached  bool      `json:"cached"`
}

type ChatReply struct {
	Reply   string    `json:"reply"`
	Model   string    `json:"model"`
	Sources []*Source `json:"sources"`
	Cached  bool      `json:"cached"`
}

type ChatSession struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Pinned    bool   `json:"pinned"`
	UpdatedAt string `json:"updatedAt"`
}

type Message struct {
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Source struct {
	ID    string  `json:"id"`
	Title *string `json:"title,omitempty"`
	Text  string  `json:"text"`
	Score float64 `json:"score"`
}

type Subscription struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
