// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type AccountSnapshot struct {
	ID                 string   `json:"id"`
	Equity             float64  `json:"equity"`
	Cash               float64  `json:"cash"`
	BuyingPower        float64  `json:"buyingPower"`
	OptionsBuyingPower *float64 `json:"optionsBuyingPower,omitempty"`
	DayPnl             *float64 `json:"dayPnl,omitempty"`
	OpenPositionsCount int      `json:"openPositionsCount"`
	CreatedAt          string   `json:"createdAt"`
}

type Decision struct {
	ID         string  `json:"id"`
	Ticker     string  `json:"ticker"`
	RunDate    string  `json:"runDate"`
	Direction  string  `json:"direction"`
	Confidence float64 `json:"confidence"`
	Summary    string  `json:"summary"`
	FullReport string  `json:"fullReport"`
	CreatedAt  string  `json:"createdAt"`
}

type Leg struct {
	Side     string  `json:"side"`
	Right    string  `json:"right"`
	Strike   float64 `json:"strike"`
	Expiry   string  `json:"expiry"`
	Symbol   string  `json:"symbol"`
	RatioQty int     `json:"ratioQty"`
}

type Mutation struct {
}

type Query struct {
}

type RiskGateEvent struct {
	ID        string  `json:"id"`
	TradeID   *string `json:"tradeId,omitempty"`
	GateName  string  `json:"gateName"`
	Passed    bool    `json:"passed"`
	Reason    string  `json:"reason"`
	CreatedAt string  `json:"createdAt"`
}

type Subscription struct {
}

type Trade struct {
	ID            string   `json:"id"`
	DecisionID    *string  `json:"decisionId,omitempty"`
	Ticker        string   `json:"ticker"`
	Strategy      string   `json:"strategy"`
	Legs          []*Leg   `json:"legs"`
	Expiry        string   `json:"expiry"`
	Quantity      int      `json:"quantity"`
	CreditDebit   string   `json:"creditDebit"`
	NetPremium    float64  `json:"netPremium"`
	MaxProfit     float64  `json:"maxProfit"`
	MaxLoss       float64  `json:"maxLoss"`
	Status        string   `json:"status"`
	AlpacaOrderID *string  `json:"alpacaOrderId,omitempty"`
	RealizedPnl   *float64 `json:"realizedPnl,omitempty"`
	Rationale     *string  `json:"rationale,omitempty"`
	OpenedAt      *string  `json:"openedAt,omitempty"`
	ClosedAt      *string  `json:"closedAt,omitempty"`
	CreatedAt     string   `json:"createdAt"`
}
